{% set version = '1.12.2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mirtcat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mirtCAT_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mirtCAT/mirtCAT_{{ version }}.tar.gz
  sha256: 26c0de3f0c54b57005a61ba2804fd2361ab2c2fff2281dc73039d9d09292ab77

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'           # [win]
    - '*/Rblas.dll'       # [win]
    - '*/Rlapack.dll'     # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-lattice
    - r-lpsolve
    - r-markdown
    - r-mirt >=1.37
    - r-pbapply
    - r-shiny >=1.0.1
    - libblas
    - liblapack
  run:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-lattice
    - r-lpsolve
    - r-markdown
    - r-mirt >=1.37
    - r-pbapply
    - r-shiny >=1.0.1

test:
  commands:
    - $R -e "library('mirtCAT')"           # [not win]
    - "\"%R%\" -e \"library('mirtCAT')\""  # [win]

about:
  home: https://github.com/philchalmers/mirtCAT, https://github.com/philchalmers/mirtCAT/wiki,
    https://groups.google.com/forum/#!forum/mirt-package
  license: GPL-3.0-or-later
  summary: Provides tools to generate an HTML interface for creating adaptive and non-adaptive
    educational and psychological tests using the shiny package (Chalmers (2016) <doi:10.18637/jss.v071.i05>).
    Suitable for applying unidimensional and multidimensional computerized adaptive
    tests (CAT) using item response theory methodology and for creating simple questionnaires
    forms to collect response data directly in R. Additionally, optimal test designs
    (e.g., "shadow testing") are supported for tests which contain a large number of
    item selection constraints. Finally, package contains tools useful for performing
    Monte Carlo simulations for studying the behavior of computerized adaptive test
    banks.
  license: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - frankier

# Package: mirtCAT
# Version: 1.12.2
# Type: Package
# Title: Computerized Adaptive Testing with Multidimensional Item Response Theory
# Authors@R: c(person("Phil", family="Chalmers", email = "rphilip.chalmers@gmail.com", role = c("aut", "cre"), comment = c(ORCID="0000-0001-5332-2810")), person("Magnus",family="Nordmo",email = "magnus.nordmo@psykologi.uio.no", role = "ctb", comment = c(ORCID="0000-0002-1977-1038")))
# Description: Provides tools to generate an HTML interface for creating adaptive and non-adaptive educational and psychological tests using the shiny package (Chalmers (2016) <doi:10.18637/jss.v071.i05>). Suitable for applying unidimensional and multidimensional computerized adaptive tests (CAT) using item response theory methodology and for creating simple questionnaires forms to collect response data directly in R. Additionally, optimal test designs (e.g., "shadow testing") are supported for tests which contain a large number of item selection constraints. Finally, package contains tools useful for performing Monte Carlo simulations for studying the behavior of computerized adaptive test banks.
# Depends: mirt (>= 1.37), shiny (>= 1.0.1)
# Imports: lattice, stats, Rcpp, methods, markdown, pbapply, lpSolve
# Suggests: shinythemes, parallel, knitr
# Encoding: UTF-8
# ByteCompile: yes
# LazyLoad: yes
# VignetteBuilder: knitr
# LinkingTo: Rcpp, RcppArmadillo
# License: GPL (>= 3)
# Repository: CRAN
# Maintainer: Phil Chalmers <rphilip.chalmers@gmail.com>
# URL: https://github.com/philchalmers/mirtCAT, https://github.com/philchalmers/mirtCAT/wiki, https://groups.google.com/forum/#!forum/mirt-package
# BugReports: https://github.com/philchalmers/mirtCAT/issues?state=open
# RoxygenNote: 7.1.1
# NeedsCompilation: yes
# Packaged: 2022-08-10 15:45:37 UTC; phil
# Author: Phil Chalmers [aut, cre] (<https://orcid.org/0000-0001-5332-2810>), Magnus Nordmo [ctb] (<https://orcid.org/0000-0002-1977-1038>)
# Date/Publication: 2022-08-11 10:10:10 UTC
